/**
 * Question Bank for Sentence Impostors
 * 25 questions across Easy / Medium / Hard difficulties.
 * Some rounds include an "impostor word" that must be excluded.
 */
const questions = [
  // ─── EASY ───────────────────────────────────────────────────────────────────
  {
    id: 1,
    sentence: "The cat sat on the mat.",
    scrambledWords: ["on", "sat", "The", "mat", "the", "cat"],
    difficulty: "easy",
    hasImpostorWord: false,
    impostorWord: null,
    grammarExplanation: "Simple sentence: Subject (The cat) + Verb (sat) + Prepositional phrase (on the mat). Very common sentence pattern!",
    category: "everyday",
  },
  {
    id: 2,
    sentence: "She reads a book every day.",
    scrambledWords: ["reads", "day", "She", "every", "a", "book"],
    difficulty: "easy",
    hasImpostorWord: false,
    impostorWord: null,
    grammarExplanation: "Simple present tense: Subject (She) + Verb (reads) + Object (a book) + Frequency adverb (every day).",
    category: "habits",
  },
  {
    id: 3,
    sentence: "The sun rises in the east.",
    scrambledWords: ["The", "in", "sun", "the", "rises", "east"],
    difficulty: "easy",
    hasImpostorWord: false,
    impostorWord: null,
    grammarExplanation: "A general truth sentence: Subject (The sun) + Verb (rises) + Prepositional phrase (in the east). Facts use simple present.",
    category: "nature",
  },
  {
    id: 4,
    sentence: "He plays football with his friends.",
    scrambledWords: ["He", "football", "friends", "his", "plays", "with"],
    difficulty: "easy",
    hasImpostorWord: false,
    impostorWord: null,
    grammarExplanation: "Subject (He) + Verb (plays) + Object (football) + Prepositional phrase (with his friends).",
    category: "sports",
  },
  {
    id: 5,
    sentence: "Birds sing beautifully in the morning.",
    scrambledWords: ["Birds", "morning", "sing", "the", "in", "beautifully"],
    difficulty: "easy",
    hasImpostorWord: false,
    impostorWord: null,
    grammarExplanation: "Subject (Birds) + Verb (sing) + Adverb of manner (beautifully) + Prepositional phrase of time (in the morning).",
    category: "nature",
  },
  {
    id: 6,
    sentence: "The children played in the park happily.",
    scrambledWords: ["The", "in", "children", "park", "played", "happily", "the"],
    difficulty: "easy",
    hasImpostorWord: false,
    impostorWord: null,
    grammarExplanation: "Past tense: Subject (The children) + Verb (played) + Location (in the park) + Manner adverb (happily).",
    category: "childhood",
  },

  // ─── MEDIUM ──────────────────────────────────────────────────────────────────
  {
    id: 7,
    sentence: "Despite the heavy rain, the determined players continued their match without complaint.",
    scrambledWords: [
      "heavy", "the", "without", "match", "complaint", "the",
      "Despite", "determined", "players", "rain", "their", "continued",
    ],
    difficulty: "medium",
    hasImpostorWord: false,
    impostorWord: null,
    grammarExplanation: "Begins with a concessive phrase 'Despite the heavy rain', then the main clause shows the contrast — players kept going anyway.",
    category: "perseverance",
  },
  {
    id: 8,
    sentence: "The curious children discovered a hidden path behind the old library.",
    scrambledWords: [
      "The", "children", "path", "behind", "old", "hidden",
      "a", "curious", "library", "discovered", "the",
    ],
    difficulty: "medium",
    hasImpostorWord: false,
    impostorWord: null,
    grammarExplanation: "Subject with adjective (The curious children) + Past tense verb (discovered) + Object phrase + Prepositional phrase (behind the old library).",
    category: "adventure",
  },
  {
    id: 9,
    sentence: "She quickly finished her homework before her favorite show started.",
    scrambledWords: [
      "She", "homework", "her", "before", "quickly", "show",
      "started", "finished", "favorite", "her",
    ],
    difficulty: "medium",
    hasImpostorWord: false,
    impostorWord: null,
    grammarExplanation: "Adverb (quickly) placed right after the subject. 'Before' is a subordinating conjunction creating a time clause.",
    category: "everyday",
  },
  {
    id: 10,
    sentence: "Although the journey was long, they arrived safely at their destination.",
    scrambledWords: [
      "the", "safely", "Although", "long", "at", "their",
      "journey", "arrived", "they", "was", "destination",
    ],
    difficulty: "medium",
    hasImpostorWord: false,
    impostorWord: null,
    grammarExplanation: "'Although' introduces a concessive subordinate clause of contrast. A comma separates it from the main clause.",
    category: "travel",
  },
  {
    id: 11,
    sentence: "The ancient temple stood silently at the top of the misty mountain.",
    scrambledWords: [
      "The", "silently", "at", "ancient", "misty", "of",
      "temple", "stood", "top", "the", "mountain", "the",
    ],
    difficulty: "medium",
    hasImpostorWord: false,
    impostorWord: null,
    grammarExplanation: "Subject + past verb + adverb (silently) + chained prepositional phrases (at the top / of the misty mountain).",
    category: "history",
  },
  {
    id: 12,
    sentence: "Without hesitation, the brave firefighter rushed into the burning building.",
    scrambledWords: [
      "hesitation", "Without", "brave", "into", "the",
      "firefighter", "burning", "rushed", "building", "the",
    ],
    difficulty: "medium",
    hasImpostorWord: false,
    impostorWord: null,
    grammarExplanation: "'Without hesitation' is a fronted adverbial that starts the sentence before a comma, then the subject and main verb follow.",
    category: "heroism",
  },
  {
    id: 13,
    sentence: "Learning a new language requires patience, dedication, and consistent practice.",
    scrambledWords: [
      "a", "language", "Learning", "patience", "dedication",
      "new", "practice", "requires", "consistent", "and",
    ],
    difficulty: "medium",
    hasImpostorWord: false,
    impostorWord: null,
    grammarExplanation: "Gerund phrase (Learning a new language) acts as the sentence subject. A series of three nouns follows 'requires'.",
    category: "education",
  },
  {
    id: 14,
    sentence: "The golden leaves fell gently from the trees as autumn arrived.",
    scrambledWords: [
      "The", "fell", "leaves", "from", "golden",
      "trees", "as", "arrived", "gently", "autumn", "the",
    ],
    difficulty: "medium",
    hasImpostorWord: false,
    impostorWord: null,
    grammarExplanation: "Main clause (The golden leaves fell gently from the trees) + adverbial time clause (as autumn arrived).",
    category: "nature",
  },
  {
    id: 15,
    sentence: "By working together, the students completed the science project successfully.",
    scrambledWords: [
      "the", "working", "By", "project", "students",
      "successfully", "together", "science", "completed", "the",
    ],
    difficulty: "medium",
    hasImpostorWord: false,
    impostorWord: null,
    grammarExplanation: "'By working together' is a gerund prepositional phrase used as a fronted adverbial explaining how the action was done.",
    category: "teamwork",
  },
  {
    id: 16,
    sentence: "The young scientist made an unexpected discovery that changed everything.",
    scrambledWords: [
      "The", "made", "young", "scientist", "discovery",
      "an", "unexpected", "that", "changed", "everything",
    ],
    difficulty: "medium",
    hasImpostorWord: false,
    impostorWord: null,
    grammarExplanation: "Main clause + relative clause (that changed everything) modifying the noun 'discovery'. 'That' connects both clauses.",
    category: "science",
  },

  // ─── HARD ────────────────────────────────────────────────────────────────────
  {
    id: 17,
    sentence: "Despite numerous obstacles, the ambitious entrepreneur transformed her innovative idea into a thriving business.",
    scrambledWords: [
      "numerous", "Despite", "ambitious", "into", "obstacles", "transformed",
      "a", "her", "entrepreneur", "thriving", "business", "idea", "innovative", "the",
    ],
    difficulty: "hard",
    hasImpostorWord: false,
    impostorWord: null,
    grammarExplanation: "Complex sentence: fronted concessive phrase + subject with adjective + verb + direct object with adjectives + prepositional phrase.",
    category: "business",
  },
  {
    id: 18,
    sentence: "Having thoroughly analyzed the complex data, the researchers published their groundbreaking findings.",
    scrambledWords: [
      "thoroughly", "Having", "the", "data", "complex", "their",
      "analyzed", "researchers", "findings", "published", "groundbreaking", "the",
    ],
    difficulty: "hard",
    hasImpostorWord: false,
    impostorWord: null,
    grammarExplanation: "Perfect participial phrase (Having analyzed...) implies the first action completed before the main verb 'published'.",
    category: "science",
  },
  {
    id: 19,
    sentence: "Neither the harsh winter weather nor the difficult terrain could stop the mountaineers.",
    scrambledWords: [
      "the", "harsh", "Neither", "difficult", "terrain", "could",
      "weather", "stop", "nor", "winter", "the", "mountaineers", "the",
    ],
    difficulty: "hard",
    hasImpostorWord: false,
    impostorWord: null,
    grammarExplanation: "Correlative conjunctions 'Neither...nor' join two noun phrases as a compound subject. The verb 'could stop' applies to both.",
    category: "adventure",
  },
  {
    id: 20,
    sentence: "Although technology has drastically changed communication, face-to-face interaction remains irreplaceable.",
    scrambledWords: [
      "has", "Although", "technology", "changed", "communication",
      "face-to-face", "drastically", "interaction", "remains", "irreplaceable",
    ],
    difficulty: "hard",
    hasImpostorWord: false,
    impostorWord: null,
    grammarExplanation: "'Although' clause presents a known fact; the main clause states the contrasting truth — face-to-face interaction cannot be replaced.",
    category: "technology",
  },
  {
    id: 21,
    sentence: "The sophisticated algorithm efficiently processed millions of data points in mere seconds.",
    scrambledWords: [
      "The", "millions", "of", "sophisticated", "processed", "in",
      "algorithm", "mere", "data", "efficiently", "seconds", "points",
    ],
    difficulty: "hard",
    hasImpostorWord: false,
    impostorWord: null,
    grammarExplanation: "Subject with adjective + verb + adverb (efficiently) + object phrase + prepositional phrase of time.",
    category: "technology",
  },
  {
    id: 22,
    sentence: "Surrounded by ancient redwood trees, the tiny cabin offered visitors a peaceful retreat from city life.",
    scrambledWords: [
      "by", "Surrounded", "ancient", "the", "trees", "redwood", "cabin",
      "offered", "tiny", "city", "visitors", "a", "from", "peaceful", "retreat", "life",
    ],
    difficulty: "hard",
    hasImpostorWord: false,
    impostorWord: null,
    grammarExplanation: "Participial phrase (Surrounded by ancient redwood trees) + main clause with indirect object (visitors) and direct object (a peaceful retreat).",
    category: "nature",
  },

  // ─── IMPOSTOR WORD ROUNDS ─────────────────────────────────────────────────────
  {
    id: 23,
    sentence: "The excited crowd cheered as the athlete crossed the finishing line.",
    scrambledWords: [
      "The", "crowd", "cheered", "excited", "as", "athlete",
      "crossed", "the", "finishing", "line", "swimming", "the",
    ],
    difficulty: "medium",
    hasImpostorWord: true,
    impostorWord: "swimming",
    grammarExplanation: "🕵️ 'swimming' is the impostor! Main clause + time clause (as the athlete crossed the finishing line). 'As' is a subordinating conjunction of time.",
    category: "sports",
  },
  {
    id: 24,
    sentence: "Against all expectations, the underdog team won the championship.",
    scrambledWords: [
      "Against", "all", "expectations", "the", "underdog",
      "team", "won", "the", "championship", "loudly",
    ],
    difficulty: "medium",
    hasImpostorWord: true,
    impostorWord: "loudly",
    grammarExplanation: "🕵️ 'loudly' is the impostor! 'Against all expectations' is a fronted prepositional phrase of contrast, then subject + verb + object.",
    category: "sports",
  },
  {
    id: 25,
    sentence: "The mysterious letter arrived at midnight with no return address.",
    scrambledWords: [
      "The", "mysterious", "letter", "arrived", "at",
      "midnight", "with", "no", "return", "address", "dancing",
    ],
    difficulty: "easy",
    hasImpostorWord: true,
    impostorWord: "dancing",
    grammarExplanation: "🕵️ 'dancing' is the impostor! Subject + verb + two prepositional phrases (at midnight) and (with no return address).",
    category: "mystery",
  },
];

module.exports = questions;
